// examples/angular/app.component.ts
import { Component, OnInit } from '@angular/core';
import { GlassMorphismService } from 'glassmorphic-kit';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'Glass Morphism Angular Demo';
  selectedVariant: 'light' | 'medium' | 'heavy' | 'subtle' | 'dramatic' = 'medium';
  showModal = false;
  inputValue = '';

  variants = [
    { name: 'Light', variant: 'light' as const },
    { name: 'Medium', variant: 'medium' as const },
    { name: 'Heavy', variant: 'heavy' as const },
    { name: 'Subtle', variant: 'subtle' as const },
    { name: 'Dramatic', variant: 'dramatic' as const },
  ];

  glassConfig = {
    blur: 12,
    opacity: 0.15,
    hoverEffect: true,
    responsive: true
  };

  customConfig = {
    blur: 20,
    opacity: 0.25,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 20,
    hoverEffect: true,
    hoverBlur: 25,
    hoverOpacity: 0.3
  };

  constructor(private glassMorphismService: GlassMorphismService) {}

  ngOnInit(): void {
    // Component initialization
  }

  selectVariant(variant: 'light' | 'medium' | 'heavy' | 'subtle' | 'dramatic'): void {
    this.selectedVariant = variant;
  }

  openModal(): void {
    this.showModal = true;
  }

  closeModal(): void {
    this.showModal = false;
  }

  onInputChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.inputValue = target.value;
  }

  onSubmit(): void {
    console.log('Form submitted with value:', this.inputValue);
    // Handle form submission
  }
}

<div class="app">
  <!-- Hero Section -->
  <section class="hero">
    <div class="hero-content">
      <glass-morphism
        [variant]="'dramatic'"
        [ngStyle]="{
          'padding': '40px',
          'text-align': 'center',
          'max-width': '600px',
          'margin': '0 auto'
        }"
      >
        <h1>Glass Morphism Showcase</h1>
        <p>Beautiful Apple-inspired glass effects for React and Angular</p>
        <glass-button
          (click)="openModal()"
          [ngStyle]="{ 'margin-top': '20px' }"
        >
          Open Modal
        </glass-button>
      </glass-morphism>
    </div>
  </section>

  <!-- Variants Section -->
  <section class="variants-section">
    <div class="container">
      <h2>Pre-configured Variants</h2>
      <div class="variants-grid">
        <glass-morphism-light
          *ngFor="let variant of variants"
          [key]="variant.variant"
          [ngStyle]="{
            'padding': '24px',
            'text-align': 'center',
            'cursor': 'pointer',
            'transition': 'transform 0.3s ease'
          }"
          [ngClass]="selectedVariant === variant.variant ? 'selected' : ''"
          (click)="selectVariant(variant.variant)"
        >
          <h3>{{ variant.name }}</h3>
          <p>Click to select this variant</p>
        </glass-morphism-light>
      </div>
    </div>
  </section>

  <!-- Presets Section -->
  <section class="presets-section">
    <div class="container">
      <h2>Pre-built Presets</h2>
      <div class="presets-grid">
        <glass-card>
          <h3>Glass Card</h3>
          <p>Perfect for content cards with glass morphism effects.</p>
          <glass-button [ngStyle]="{ 'margin-top': '16px' }">
            Action Button
          </glass-button>
        </glass-card>

        <glass-morphism
          [preset]="'modal'"
          [ngStyle]="{ 'max-width': '400px', 'margin': '0 auto' }"
        >
          <h3>Modal Preset</h3>
          <p>Ready-to-use modal styling with glass effects.</p>
          <div [ngStyle]="{ 'display': 'flex', 'gap': '12px', 'margin-top': '20px' }">
            <glass-button>Cancel</glass-button>
            <glass-button>Confirm</glass-button>
          </div>
        </glass-morphism>

        <glass-morphism
          [preset]="'tooltip'"
          [ngStyle]="{ 'max-width': '250px', 'margin': '0 auto' }"
        >
          <h4>Tooltip Preset</h4>
          <p>Lightweight tooltip with subtle glass effects.</p>
        </glass-morphism>
      </div>
    </div>
  </section>

  <!-- Interactive Section -->
  <section class="interactive-section">
    <div class="container">
      <h2>Interactive Examples</h2>
      <div class="interactive-grid">
        <glass-morphism
          [variant]="selectedVariant"
          [ngStyle]="{ 'padding': '24px' }"
        >
          <h3>Dynamic Variant</h3>
          <p>This component changes based on the selected variant above.</p>
          <p>Current variant: <strong>{{ selectedVariant }}</strong></p>
        </glass-morphism>

        <glass-morphism
          [config]="customConfig"
          [ngStyle]="{ 'padding': '24px' }"
        >
          <h3>Custom Configuration</h3>
          <p>This card uses custom glass morphism configuration!</p>
        </glass-morphism>

        <glass-morphism
          [config]="glassConfig"
          [ngStyle]="{ 'padding': '24px' }"
        >
          <h3>Service Configuration</h3>
          <p>This card uses the default service configuration.</p>
        </glass-morphism>
      </div>
    </div>
  </section>

  <!-- Form Section -->
  <section class="form-section">
    <div class="container">
      <h2>Form Elements</h2>
      <glass-morphism
        [ngStyle]="{
          'padding': '32px',
          'max-width': '500px',
          'margin': '0 auto'
        }"
      >
        <h3>Contact Form</h3>
        <form (ngSubmit)="onSubmit()">
          <div [ngStyle]="{ 'margin-bottom': '20px' }">
            <label [ngStyle]="{ 'display': 'block', 'margin-bottom': '8px' }">
              Name
            </label>
            <glass-morphism
              [preset]="'input'"
              [ngStyle]="{ 'width': '100%' }"
            >
              <input
                type="text"
                placeholder="Enter your name"
                [value]="inputValue"
                (input)="onInputChange($event)"
                [ngStyle]="{
                  'width': '100%',
                  'border': 'none',
                  'background': 'transparent',
                  'outline': 'none',
                  'padding': '12px 16px',
                  'font-size': '16px'
                }"
              />
            </glass-morphism>
          </div>
          
          <div [ngStyle]="{ 'margin-bottom': '20px' }">
            <label [ngStyle]="{ 'display': 'block', 'margin-bottom': '8px' }">
              Email
            </label>
            <glass-morphism
              [preset]="'input'"
              [ngStyle]="{ 'width': '100%' }"
            >
              <input
                type="email"
                placeholder="Enter your email"
                [ngStyle]="{
                  'width': '100%',
                  'border': 'none',
                  'background': 'transparent',
                  'outline': 'none',
                  'padding': '12px 16px',
                  'font-size': '16px'
                }"
              />
            </glass-morphism>
          </div>
          
          <div [ngStyle]="{ 'margin-bottom': '20px' }">
            <label [ngStyle]="{ 'display': 'block', 'margin-bottom': '8px' }">
              Message
            </label>
            <glass-morphism
              [preset]="'input'"
              [ngStyle]="{ 'width': '100%' }"
            >
              <textarea
                placeholder="Enter your message"
                [ngStyle]="{
                  'width': '100%',
                  'border': 'none',
                  'background': 'transparent',
                  'outline': 'none',
                  'padding': '12px 16px',
                  'font-size': '16px',
                  'min-height': '100px',
                  'resize': 'vertical'
                }"
              ></textarea>
            </glass-morphism>
          </div>
          
          <glass-button type="submit">
            Send Message
          </glass-button>
        </form>
      </glass-morphism>
    </div>
  </section>

  <!-- Modal -->
  <div 
    *ngIf="showModal" 
    class="modal-overlay" 
    (click)="closeModal()"
  >
    <glass-modal
      (click)="$event.stopPropagation()"
      [ngStyle]="{ 'max-width': '500px', 'margin': '50px auto' }"
    >
      <h2>Glass Modal</h2>
      <p>This is a beautiful glass morphism modal dialog!</p>
      <p>Click outside to close or use the button below.</p>
      <glass-button
        (click)="closeModal()"
        [ngStyle]="{ 'margin-top': '20px' }"
      >
        Close Modal
      </glass-button>
    </glass-modal>
  </div>
</div>

// examples/react/App.tsx
import React, { useState } from 'react';
import {
  GlassMorphism,
  GlassMorphismLight,
  GlassMorphismMedium,
  GlassMorphismHeavy,
  GlassMorphismSubtle,
  GlassMorphismDramatic,
  GlassCard,
  GlassModal,
  GlassButton,
  GlassInput,
  useGlassMorphism
} from 'glassmorphic-kit';
import './App.css';

const App: React.FC = () => {
  const [showModal, setShowModal] = useState(false);
  const [inputValue, setInputValue] = useState('');
  const [selectedVariant, setSelectedVariant] = useState<'light' | 'medium' | 'heavy' | 'subtle' | 'dramatic'>('medium');

  // Custom hook example
  const { styles: customStyles, eventHandlers } = useGlassMorphism({
    variant: 'medium',
    hoverEffect: true,
    blur: 15,
    opacity: 0.2,
  });

  const variants = [
    { name: 'Light', component: GlassMorphismLight, variant: 'light' as const },
    { name: 'Medium', component: GlassMorphismMedium, variant: 'medium' as const },
    { name: 'Heavy', component: GlassMorphismHeavy, variant: 'heavy' as const },
    { name: 'Subtle', component: GlassMorphismSubtle, variant: 'subtle' as const },
    { name: 'Dramatic', component: GlassMorphismDramatic, variant: 'dramatic' as const },
  ];

  return (
    <div className="app">
      {/* Hero Section */}
      <section className="hero">
        <div className="hero-content">
          <GlassMorphism
            variant="dramatic"
            style={{
              padding: '40px',
              textAlign: 'center',
              maxWidth: '600px',
              margin: '0 auto'
            }}
          >
            <h1>Glass Morphism Showcase</h1>
            <p>Beautiful Apple-inspired glass effects for React and Angular</p>
            <GlassButton
              onClick={() => setShowModal(true)}
              style={{ marginTop: '20px' }}
            >
              Open Modal
            </GlassButton>
          </GlassMorphism>
        </div>
      </section>

      {/* Variants Section */}
      <section className="variants-section">
        <div className="container">
          <h2>Pre-configured Variants</h2>
          <div className="variants-grid">
            {variants.map(({ name, component: Component, variant }) => (
              <Component
                key={variant}
                style={{
                  padding: '24px',
                  textAlign: 'center',
                  cursor: 'pointer',
                  transition: 'transform 0.3s ease'
                }}
                onClick={() => setSelectedVariant(variant)}
                className={selectedVariant === variant ? 'selected' : ''}
              >
                <h3>{name}</h3>
                <p>Click to select this variant</p>
              </Component>
            ))}
          </div>
        </div>
      </section>

      {/* Presets Section */}
      <section className="presets-section">
        <div className="container">
          <h2>Pre-built Presets</h2>
          <div className="presets-grid">
            <GlassCard>
              <h3>Glass Card</h3>
              <p>Perfect for content cards with glass morphism effects.</p>
              <GlassButton style={{ marginTop: '16px' }}>
                Action Button
              </GlassButton>
            </GlassCard>

            <GlassMorphism
              preset="modal"
              style={{ maxWidth: '400px', margin: '0 auto' }}
            >
              <h3>Modal Preset</h3>
              <p>Ready-to-use modal styling with glass effects.</p>
              <div style={{ display: 'flex', gap: '12px', marginTop: '20px' }}>
                <GlassButton>Cancel</GlassButton>
                <GlassButton>Confirm</GlassButton>
              </div>
            </GlassMorphism>

            <GlassMorphism
              preset="tooltip"
              style={{ maxWidth: '250px', margin: '0 auto' }}
            >
              <h4>Tooltip Preset</h4>
              <p>Lightweight tooltip with subtle glass effects.</p>
            </GlassMorphism>
          </div>
        </div>
      </section>

      {/* Interactive Section */}
      <section className="interactive-section">
        <div className="container">
          <h2>Interactive Examples</h2>
          <div className="interactive-grid">
            <GlassMorphism
              variant={selectedVariant}
              style={{ padding: '24px' }}
            >
              <h3>Dynamic Variant</h3>
              <p>This component changes based on the selected variant above.</p>
              <p>Current variant: <strong>{selectedVariant}</strong></p>
            </GlassMorphism>

            <GlassMorphism
              style={{
                padding: '24px',
                background: 'linear-gradient(45deg, rgba(255,255,255,0.1), rgba(255,255,255,0.2))'
              }}
              hoverEffect={true}
              hoverBlur={20}
              hoverOpacity={0.3}
            >
              <h3>Custom Hover Effects</h3>
              <p>Hover over this card to see enhanced glass effects!</p>
            </GlassMorphism>

            <div style={customStyles} {...eventHandlers}>
              <h3>Custom Hook Example</h3>
              <p>This card uses the useGlassMorphism hook for styling.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Form Section */}
      <section className="form-section">
        <div className="container">
          <h2>Form Elements</h2>
          <GlassMorphism
            style={{
              padding: '32px',
              maxWidth: '500px',
              margin: '0 auto'
            }}
          >
            <h3>Contact Form</h3>
            <form>
              <div style={{ marginBottom: '20px' }}>
                <label style={{ display: 'block', marginBottom: '8px' }}>
                  Name
                </label>
                <GlassInput
                  type="text"
                  placeholder="Enter your name"
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                />
              </div>
              <div style={{ marginBottom: '20px' }}>
                <label style={{ display: 'block', marginBottom: '8px' }}>
                  Email
                </label>
                <GlassInput
                  type="email"
                  placeholder="Enter your email"
                />
              </div>
              <div style={{ marginBottom: '20px' }}>
                <label style={{ display: 'block', marginBottom: '8px' }}>
                  Message
                </label>
                <GlassInput
                  as="textarea"
                  placeholder="Enter your message"
                  style={{ minHeight: '100px', resize: 'vertical' }}
                />
              </div>
              <GlassButton type="submit">
                Send Message
              </GlassButton>
            </form>
          </GlassMorphism>
        </div>
      </section>

      {/* Modal */}
      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <GlassModal
            onClick={(e) => e.stopPropagation()}
            style={{ maxWidth: '500px', margin: '50px auto' }}
          >
            <h2>Glass Modal</h2>
            <p>This is a beautiful glass morphism modal dialog!</p>
            <p>Click outside to close or use the button below.</p>
            <GlassButton
              onClick={() => setShowModal(false)}
              style={{ marginTop: '20px' }}
            >
              Close Modal
            </GlassButton>
          </GlassModal>
        </div>
      )}
    </div>
  );
};

export default App;
